[package]
name = "ssg"
version = "0.1.0"
edition = "2021"

[dependencies]
# HTMLテンプレート
tera = "1.19"

# JSON（将来拡張・デバッグ用）
serde = { version = "1", features = ["derive"] }

# markdown->html
pulldown-cmark = "0.10"
serde_yaml = "0.9"
walkdir = "2"